# Generated by Django 6.0.3 on 2026-03-22 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiali', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learning_focus',
            field=models.CharField(blank=True, default='', help_text='Optional: course, topic, or semester focus.', max_length=200),
        ),
        migrations.AddField(
            model_name='supply',
            name='subject_area',
            field=models.CharField(blank=True, default='', help_text='Study area for this item so peers in the same field can find it.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_major',
            field=models.CharField(blank=True, default='', help_text='What you study (e.g. Computer Science, Biology).', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(help_text='Subject or field this material belongs to (often matches what you study).', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supply',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to=settings.AUTH_USER_MODEL),
        ),
    ]
