# Generated by Django 6.0.3 on 2026-03-22 14:47

from django.db import migrations, models


def mark_existing_profiles_verified(apps, schema_editor):
    Profile = apps.get_model('materiali', 'Profile')
    Profile.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('materiali', '0002_profile_supply_learning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_profiles_verified, migrations.RunPython.noop),
    ]
